; Console Select Menu for GTA IV The Complete Edition.
; Set this when you want to leave the PC title menu behind.
bSkipTitleMenu FALSE
; Set this when you want the Complete Edition logo to own the intro.
bUseCELogo     TRUE
